In [4]:
import numpy as np
import pandas as pd

In [16]:
df = pd.read_csv('SalariesKNN.csv')
df

    Age  Salary  Experience  Class
0  25.0    50.0         2.0      0
1  28.0     NaN         4.0      1
2  32.0    60.0         NaN      0
3   NaN    80.0         6.0      1
4  40.0    90.0        10.0      1
5  30.0    55.0         5.0      0
6  27.0    52.0         NaN      0
7   NaN   120.0        12.0      1
8  29.0     NaN         3.0      0
9  35.0    70.0         7.0      1

In [27]:
dfforwardfill = df.ffill()
dfforwardfill

    Age  Salary  Experience  Class
0  25.0    50.0         2.0      0
1  28.0    50.0         4.0      1
2  32.0    60.0         4.0      0
3  32.0    80.0         6.0      1
4  40.0    90.0        10.0      1
5  30.0    55.0         5.0      0
6  27.0    52.0         5.0      0
7  27.0   120.0        12.0      1
8  29.0   120.0         3.0      0
9  35.0    70.0         7.0      1

In [29]:
backwardfill =df.bfill()
backwardfill

    Age  Salary  Experience  Class
0  25.0    50.0         2.0      0
1  28.0    60.0         4.0      1
2  32.0    60.0         6.0      0
3  40.0    80.0         6.0      1
4  40.0    90.0        10.0      1
5  30.0    55.0         5.0      0
6  27.0    52.0        12.0      0
7  29.0   120.0        12.0      1
8  29.0    70.0         3.0      0
9  35.0    70.0         7.0      1