In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('data_science_job.csv')
df

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,20.0,NaN,NaN,36.0,1
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15.0,50-99,Pvt Ltd,47.0,0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5.0,NaN,NaN,83.0,0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,0.0,NaN,Pvt Ltd,52.0,1
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,20.0,50-99,Funded Startup,8.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
19153,7386,city_173,0.878,Male,No relevent experience,no_enrollment,Graduate,Humanities,14.0,NaN,NaN,42.0,1
19154,31398,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,14.0,NaN,NaN,52.0,1
19155,24576,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,20.0,50-99,Pvt Ltd,44.0,0
19156,5756,city_65,0.802,Male,Has relevent experience,no_enrollment,High School,NaN,0.0,500-999,Pvt Ltd,97.0,0
19157,23834,city_67,0.855,NaN,No relevent experience,no_enrollment,Primary School,NaN,2.0,NaN,NaN,127.0,0

## Check for null values

In [ ]:
df.isnull() #get False for non-null value and True for null value

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,training_hours,target
0,False,False,False,False,False,False,False,False,False,True,True,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,True,False,False,False,False,False,True,True,False,False
3,False,False,False,True,False,True,False,False,False,True,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
19153,False,False,False,False,False,False,False,False,False,True,True,False,False
19154,False,False,False,False,False,False,False,False,False,True,True,False,False
19155,False,False,False,False,False,False,False,False,False,False,False,False,False
19156,False,False,False,False,False,False,False,True,False,False,False,False,False
19157,False,False,False,True,False,False,False,True,False,True,True,False,False

## Median Imputation (Numerical Columns)

More robust to outliers than mean.

In [18]:
median_imputation = df['training_hours'].fillna(df['training_hours'].median())
median_imputation

0         36.0
1         47.0
2         83.0
3         52.0
4          8.0
         ...
19153     42.0
19154     52.0
19155     44.0
19156     97.0
19157    127.0
Name: training_hours, Length: 19158, dtype: float64

In [19]:
cols = ['city_development_index', 'experience', 'training_hours']

In [20]:
median_imputation = df[cols].fillna(df[cols].mean())
median_imputation

       city_development_index  experience  training_hours
0                       0.920        20.0            36.0
1                       0.776        15.0            47.0
2                       0.624         5.0            83.0
3                       0.789         0.0            52.0
4                       0.767        20.0             8.0
...                       ...         ...             ...
19153                   0.878        14.0            42.0
19154                   0.920        14.0            52.0
19155                   0.920        20.0            44.0
19156                   0.802         0.0            97.0
19157                   0.855         2.0           127.0

[19158 rows x 3 columns]

df['training_hours'] selects the training_hours column as a Series.

.median() computes the median value of that column.

.fillna(...) replaces all missing values (NaN) in that Series with the median.
The result is stored in median_imputation.

In [21]:
df[cols] = median_imputation
df

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,20.0,NaN,NaN,36.0,1
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15.0,50-99,Pvt Ltd,47.0,0
2,11561,city_21,0.624,Male,No relevent experience,Full time course,Graduate,STEM,5.0,NaN,NaN,83.0,0
3,33241,city_115,0.789,Male,No relevent experience,NaN,Graduate,Business Degree,0.0,NaN,Pvt Ltd,52.0,1
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,20.0,50-99,Funded Startup,8.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
19153,7386,city_173,0.878,Male,No relevent experience,no_enrollment,Graduate,Humanities,14.0,NaN,NaN,42.0,1
19154,31398,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,14.0,NaN,NaN,52.0,1
19155,24576,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,20.0,50-99,Pvt Ltd,44.0,0
19156,5756,city_65,0.802,Male,Has relevent experience,no_enrollment,High School,NaN,0.0,500-999,Pvt Ltd,97.0,0
19157,23834,city_67,0.855,Male,No relevent experience,no_enrollment,Primary School,NaN,2.0,NaN,NaN,127.0,0

## Mean Imputation (Numerical Columns)

Replaces missing values with the average of the column.

In [9]:
cols = ['city_development_index', 'experience', 'training_hours']

In [10]:
mean_imputation = df[cols].fillna(df[cols].mean())
mean_imputation

       city_development_index  experience  training_hours
0                       0.920        20.0            36.0
1                       0.776        15.0            47.0
2                       0.624         5.0            83.0
3                       0.789         0.0            52.0
4                       0.767        20.0             8.0
...                       ...         ...             ...
19153                   0.878        14.0            42.0
19154                   0.920        14.0            52.0
19155                   0.920        20.0            44.0
19156                   0.802         0.0            97.0
19157                   0.855         2.0           127.0

[19158 rows x 3 columns]

cols is a list of numeric column names, e.g. ['city_development_index', 'experience', 'training_hours'].

df[cols] selects those columns as a DataFrame.

.mean() computes the mean for each selected column, returning a Series of column means.

.fillna(df[cols].mean()) fills missing values in each column using that column’s own mean.

In [11]:
df[cols] = mean_imputation
df

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,20.0,NaN,NaN,36.0,1
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15.0,50-99,Pvt Ltd,47.0,0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5.0,NaN,NaN,83.0,0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,0.0,NaN,Pvt Ltd,52.0,1
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,20.0,50-99,Funded Startup,8.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
19153,7386,city_173,0.878,Male,No relevent experience,no_enrollment,Graduate,Humanities,14.0,NaN,NaN,42.0,1
19154,31398,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,14.0,NaN,NaN,52.0,1
19155,24576,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,20.0,50-99,Pvt Ltd,44.0,0
19156,5756,city_65,0.802,Male,Has relevent experience,no_enrollment,High School,NaN,0.0,500-999,Pvt Ltd,97.0,0
19157,23834,city_67,0.855,NaN,No relevent experience,no_enrollment,Primary School,NaN,2.0,NaN,NaN,127.0,0

## Mode Imputation (Categorical + Numerical)

Replaces missing values with the most frequent value.

In [15]:
Mode_imputation = df['gender'].fillna(df['gender'].mode()[0])
Mode_imputation

0        Male
1        Male
2        Male
3        Male
4        Male
         ...
19153    Male
19154    Male
19155    Male
19156    Male
19157    Male
Name: gender, Length: 19158, dtype: object

In [16]:
df['gender'] = Mode_imputation
df

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,20.0,NaN,NaN,36.0,1
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15.0,50-99,Pvt Ltd,47.0,0
2,11561,city_21,0.624,Male,No relevent experience,Full time course,Graduate,STEM,5.0,NaN,NaN,83.0,0
3,33241,city_115,0.789,Male,No relevent experience,NaN,Graduate,Business Degree,0.0,NaN,Pvt Ltd,52.0,1
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,20.0,50-99,Funded Startup,8.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
19153,7386,city_173,0.878,Male,No relevent experience,no_enrollment,Graduate,Humanities,14.0,NaN,NaN,42.0,1
19154,31398,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,14.0,NaN,NaN,52.0,1
19155,24576,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,20.0,50-99,Pvt Ltd,44.0,0
19156,5756,city_65,0.802,Male,Has relevent experience,no_enrollment,High School,NaN,0.0,500-999,Pvt Ltd,97.0,0
19157,23834,city_67,0.855,Male,No relevent experience,no_enrollment,Primary School,NaN,2.0,NaN,NaN,127.0,0